[Telegram]: added telegram bot for sending notifications
JV-SEP23-team1/accommodation-booking-app pull request #11
Opened 2024-01-15 08:55 UTC by TarasYurkovskyi

### Added:

- TelegramBot class
- BotInitializer class
- New dependencies for telegram
- Booking repository
- Notification service interface
- TelegramNotificationService

### Changed:

- Add new column for user model
- Change script for creating user table
- Add new methods to user repository

2024-01-15 10:40 UTC, vadymhrnk requested changes
Well done! Small points for you to consider

2024-01-15 10:40 UTC, vadymhrnk commented on src/main/resources/db/changelog/changes/01-create-users-table.yaml
> +                  name: chat_Id
I think it's better to have consistent naming and the version in model looks better to me
```
@Column(name = "chat_id", unique = true)
private Long chatId;
```

2024-01-15 10:40 UTC, vadymhrnk commented on src/main/java/com/example/accommodationbookingapp/telegram/BotInitializer.java
> +            throw new RuntimeException("Cannot initialize the Bot" + e.getMessage());
Better to put this text in constant field

2024-01-15 10:40 UTC, vadymhrnk commented on src/main/resources/application.properties
> +spring.datasource.password=DoinTheMost2005!
Better to remove this and use environment variable in IDE

2024-01-15 11:08 UTC, vadymhrnk approved these changes
LGTM

2024-01-15 18:32 UTC, annton-shakur approved these changes
Well done!

2024-01-16 07:51 UTC, Sofasmile commented on src/main/java/com/example/accommodationbookingapp/telegram/BotInitializer.java
> +            throw new RuntimeException(INIT_ERR + e.getMessage());
```suggestion
            throw new RuntimeException(INIT_ERR + e.getMessage(), e);
```

2024-01-16 07:51 UTC, Sofasmile commented on src/main/java/com/example/accommodationbookingapp/telegram/TelegramBot.java
> +    public void onUpdateReceived(Update update) {
Recommendation: try to split this method and use strategy

2024-01-16 10:21 UTC, MinoDentori approved these changes
Looks good for me

2024-01-16 10:25 UTC, merged